name: instagram_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  cloud_firestore: ^3.1.11
  firebase_core: ^1.14.0
  firebase_auth: ^3.3.12
  firebase_storage: ^10.2.10
  flutter_svg: ^1.0.3
  image_picker: ^0.8.5
  intl: ^0.17.0
  provider: ^6.0.2
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true

  assets:
    - assets/